import { getLang } from '../state.js';
import { partnerForm } from '../components/partnerForm.js';
import { testimonials, trustBadges } from '../components/testimonials.js';

export function renderAbout() {
  const E = getLang() === 'ru';

  return '' +
  // Hero
  '<div style="padding:140px 0 80px;background:linear-gradient(135deg,var(--dk),#1f2937)"><div class="con" style="text-align:center"><div class="stag" style="color:var(--c1)">' + (E ? 'О компании' : 'About us') + '</div><h1 style="font-family:var(--fd);font-size:clamp(36px,5vw,52px);color:#fff;margin-bottom:16px">' + (E ? 'Мы не просто бронируем — мы строим партнёрства' : 'We don\'t just book — we build partnerships') + '</h1><p style="color:rgba(255,255,255,.6);font-size:18px;max-width:640px;margin:0 auto;line-height:1.7">' + (E ? 'Desera Travel — это DMC нового поколения. Мы создали компанию, которую сами хотели бы видеть на рынке.' : 'Desera Travel is a next-generation DMC. We built the company we always wished existed in the market.') + '</p></div></div>' +

  // Our Story
  '<section class="sec"><div class="con" style="display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center"><div><div class="stag">' + (E ? 'Наша история' : 'Our story') + '</div><h2 style="font-family:var(--fd);font-size:28px;color:var(--dk);margin-bottom:20px">' + (E ? 'От маркетинга к миссии' : 'From marketing to a mission') + '</h2><p style="font-size:16px;line-height:1.8;color:var(--g500);margin-bottom:16px">' +
  (E ? 'Всё началось с цифр. Как маркетинговое агентство, мы больше года вели продвижение туристической компании — привлекали лиды, анализировали спрос, изучали рынок. И чем глубже мы погружались, тем яснее видели проблему.'
     : 'It all started with data. As a marketing agency, we spent over a year promoting a tourism company — generating leads, analyzing demand, studying the market. And the deeper we dug, the clearer the problem became.') + '</p><p style="font-size:16px;line-height:1.8;color:var(--g500);margin-bottom:16px">' +
  (E ? 'Большинство DMC-компаний предлагают 4-5 направлений. Максимум шесть. Но когда мы анализировали входящие заявки, картина была совсем другой — люди хотели разнообразия. Им не нужны были одни и те же маршруты. Они мечтали о Японии, спрашивали про Вьетнам, интересовались Маврикием. А компания могла предложить только то, что было в каталоге.'
     : 'Most DMC companies offer 4-5 destinations. Six at best. But when we analyzed incoming leads, the picture was completely different — people wanted variety. They didn\'t want the same old routes. They dreamed of Japan, asked about Vietnam, were curious about Mauritius. But the company could only offer what was in the catalog.') + '</p><p style="font-size:16px;line-height:1.8;color:var(--g500);margin-bottom:16px">' +
  (E ? 'Мы видели, как турагентства теряли клиентов просто потому, что не могли закрыть запрос. Человек хочет Бали — а у агентства только Турция и Египет. Хочет Мальдивы — отправляют к конкурентам. Рынок был фрагментирован: десятки узких DMC, каждый со своими 2-3 странами, и ни одного, кто объединит всё в одном месте.'
     : 'We watched agencies lose clients simply because they couldn\'t fulfill a request. A customer wants Bali — but the agency only has Turkey and Egypt. Wants the Maldives — sent to a competitor. The market was fragmented: dozens of narrow DMCs, each covering 2-3 countries, and not a single one that brings it all together.') + '</p><p style="font-size:16px;line-height:1.8;color:var(--g500);margin-bottom:16px">' +
  (E ? 'Тогда мы задали себе вопрос: почему бы не создать DMC, который даст турагентствам весь мир? Не 5 стран, не 8 — а глобальное покрытие. Чтобы любое агентство, в любом городе, могло предложить своим клиентам путешествие куда угодно — от Дубая до Токио, от Стамбула до Бали.'
     : 'That\'s when we asked ourselves: why not build a DMC that gives agencies the whole world? Not 5 countries, not 8 — but global coverage. So that any agency, in any city, could offer their clients a trip anywhere — from Dubai to Tokyo, Istanbul to Bali.') + '</p><p style="font-size:16px;line-height:1.8;color:var(--g500)">' +
  (E ? 'Так родилась Desera Travel. Наша миссия — сделать мир доступнее. Не в смысле дешевле, а в смысле ближе. Чтобы невероятные уголки планеты — рисовые террасы Вьетнама, подводный мир Мальдив, древние храмы Японии — перестали быть экзотикой и стали реальным предложением в каталоге каждого турагентства.'
     : 'That\'s how Desera Travel was born. Our mission is to make the world more reachable. Not cheaper — but closer. So that incredible corners of the planet — the rice terraces of Vietnam, the underwater world of the Maldives, the ancient temples of Japan — stop being exotic and become a real offering in every agency\'s catalog.') + '</p></div><div style="border-radius:24px;overflow:hidden"><img loading="lazy" src="https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800" alt="Desera Travel team collaboration" style="width:100%"></div></div></section>' +

  // What makes us different
  '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Чем мы отличаемся' : 'What makes us different') + '</div><h2 class="stitle">' + (E ? 'Не просто ещё один DMC' : 'Not just another DMC') + '</h2></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:40px"><div class="anim" style="padding:32px;border-radius:20px;border:1px solid var(--g200)"><h3 style="font-family:var(--fd);font-size:20px;color:var(--dk);margin-bottom:12px">' + (E ? '🎯 Мы были на вашем месте' : '🎯 We\'ve been in your shoes') + '</h3><p style="font-size:15px;line-height:1.7;color:var(--g500)">' +
  (E ? 'Наша команда — это бывшие сотрудники агентств и туроператоров. Мы понимаем давление дедлайнов, требовательных клиентов и необходимость заработать маржу. Поэтому наш сервис заточен под реальные потребности агента, а не под красивые презентации.'
     : 'Our team is made up of former agency and tour operator staff. We understand the pressure of deadlines, demanding clients, and the need to earn a margin. That\'s why our service is built around real agent needs, not flashy presentations.') + '</p></div><div class="anim" style="padding:32px;border-radius:20px;border:1px solid var(--g200)"><h3 style="font-family:var(--fd);font-size:20px;color:var(--dk);margin-bottom:12px">' + (E ? '⚡ Технологии, а не бюрократия' : '⚡ Technology, not bureaucracy') + '</h3><p style="font-size:15px;line-height:1.7;color:var(--g500)">' +
  (E ? 'Пока другие DMC отвечают по email через 48 часов, мы строим B2B-платформу с проверкой наличия в реальном времени и моментальным подтверждением. Наша цель — чтобы вы могли подтвердить бронирование клиенту, пока он ещё на линии.'
     : 'While other DMCs reply by email in 48 hours, we\'re building a B2B platform with real-time availability and instant confirmation. Our goal is for you to confirm a booking while your client is still on the phone.') + '</p></div><div class="anim" style="padding:32px;border-radius:20px;border:1px solid var(--g200)"><h3 style="font-family:var(--fd);font-size:20px;color:var(--dk);margin-bottom:12px">' + (E ? '🌍 Один партнёр — весь мир' : '🌍 One partner — the whole world') + '</h3><p style="font-size:15px;line-height:1.7;color:var(--g500)">' +
  (E ? 'Вместо 11 разных DMC в 11 странах — один контракт, один формат, одна команда. От Дубая до Токио, от Стамбула до Бали. Мы сами координируем локальных поставщиков, а вы получаете единый стандарт качества.'
     : 'Instead of 11 different DMCs in 11 countries — one contract, one format, one team. From Dubai to Tokyo, Istanbul to Bali. We coordinate local suppliers ourselves, and you get a consistent quality standard.') + '</p></div><div class="anim" style="padding:32px;border-radius:20px;border:1px solid var(--g200)"><h3 style="font-family:var(--fd);font-size:20px;color:var(--dk);margin-bottom:12px">' + (E ? '💰 Прозрачные цены' : '💰 Transparent pricing') + '</h3><p style="font-size:15px;line-height:1.7;color:var(--g500)">' +
  (E ? 'Никаких скрытых наценок и непонятных комиссий. Вы видите нетто-тариф и сами решаете, какую маржу поставить. Прямые контракты с отелями и поставщиками — значит лучшие цены без посредников.'
     : 'No hidden markups or confusing commissions. You see the net rate and decide your own margin. Direct contracts with hotels and suppliers mean the best prices without middlemen.') + '</p></div></div></div></section>' +

  // Values
  '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Ценности' : 'Values') + '</div><h2 class="stitle">' + (E ? 'Принципы, которые мы не нарушаем' : 'Principles we never break') + '</h2></div><div class="pgrid" style="grid-template-columns:repeat(4,1fr)"><div class="pc anim"><div class="pc-ic" style="background:var(--c1l)">🤝</div><div class="pt">' + (E ? 'Партнёрство' : 'Partnership') + '</div><p class="pp">' + (E ? 'Мы не считаем вас клиентом — вы наш партнёр. Ваш рост = наш рост.' : 'We don\'t see you as a client — you\'re our partner. Your growth = our growth.') + '</p></div><div class="pc anim"><div class="pc-ic" style="background:var(--c2l)">⚡</div><div class="pt">' + (E ? 'Скорость' : 'Speed') + '</div><p class="pp">' + (E ? 'Максимум 2 часа на ответ. Мы знаем: в нашей индустрии скорость решает всё.' : 'Max 2 hours to respond. We know: in our industry, speed decides everything.') + '</p></div><div class="pc anim"><div class="pc-ic" style="background:var(--c3l)">💎</div><div class="pt">' + (E ? 'Качество' : 'Quality') + '</div><p class="pp">' + (E ? 'Каждый запрос — индивидуальный проект. Мы не делаем «и так сойдёт».' : 'Every request is a unique project. We don\'t do "good enough".') + '</p></div><div class="pc anim"><div class="pc-ic" style="background:var(--gdl)">🔒</div><div class="pt">' + (E ? 'Честность' : 'Honesty') + '</div><p class="pp">' + (E ? 'Прозрачные цены, реальные сроки, честная обратная связь — даже если это не то, что хочется слышать.' : 'Transparent pricing, real timelines, honest feedback — even when it\'s not what you want to hear.') + '</p></div></div></div></section>' +

  // Numbers
  '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'В цифрах' : 'In numbers') + '</div><h2 class="stitle">' + (E ? 'Desera сегодня' : 'Desera today') + '</h2></div><div class="pgrid"><div class="pc" style="text-align:center"><div class="counter" data-target="11" data-suffix="+" style="font-family:var(--fd);font-size:48px;color:var(--c1)">0</div><p class="pp">' + (E ? 'Направлений' : 'Destinations') + '</p></div><div class="pc" style="text-align:center"><div class="counter" data-target="500" data-suffix="+" style="font-family:var(--fd);font-size:48px;color:var(--c1)">0</div><p class="pp">' + (E ? 'Отелей по нетто' : 'Hotels at net rates') + '</p></div><div class="pc" style="text-align:center"><div class="counter" data-target="200" data-suffix="+" style="font-family:var(--fd);font-size:48px;color:var(--c1)">0</div><p class="pp">' + (E ? 'Туров и экскурсий' : 'Tours & excursions') + '</p></div><div class="pc" style="text-align:center"><div class="counter" data-target="2" data-suffix="h" style="font-family:var(--fd);font-size:48px;color:var(--c1)">0</div><p class="pp">' + (E ? 'Максимум на ответ' : 'Max response time') + '</p></div></div></div></section>' +

  // How we work
  '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Как мы работаем' : 'How we work') + '</div><h2 class="stitle">' + (E ? 'От запроса до подтверждения — 4 шага' : 'From request to confirmation — 4 steps') + '</h2></div><div class="pgrid" style="grid-template-columns:repeat(4,1fr)"><div class="pc anim" style="text-align:center;position:relative"><div style="font-family:var(--fd);font-size:48px;color:var(--c1);margin-bottom:12px">01</div><div class="pt">' + (E ? 'Вы отправляете запрос' : 'You send a request') + '</div><p class="pp">' + (E ? 'Через форму, email, WhatsApp или B2B-платформу — как удобно.' : 'Via form, email, WhatsApp, or B2B platform — however you prefer.') + '</p></div><div class="pc anim" style="text-align:center"><div style="font-family:var(--fd);font-size:48px;color:var(--c1);margin-bottom:12px">02</div><div class="pt">' + (E ? 'Мы подбираем варианты' : 'We prepare options') + '</div><p class="pp">' + (E ? 'В течение 2 часов вы получаете предложение с нетто-ценами и всеми деталями.' : 'Within 2 hours you receive a proposal with net rates and full details.') + '</p></div><div class="pc anim" style="text-align:center"><div style="font-family:var(--fd);font-size:48px;color:var(--c1);margin-bottom:12px">03</div><div class="pt">' + (E ? 'Вы выбираете и продаёте' : 'You choose and sell') + '</div><p class="pp">' + (E ? 'Ставите свою маржу, отправляете клиенту. Мы не лезем в ваши отношения с клиентом.' : 'Set your margin, send to your client. We never interfere with your client relationship.') + '</p></div><div class="pc anim" style="text-align:center"><div style="font-family:var(--fd);font-size:48px;color:var(--c1);margin-bottom:12px">04</div><div class="pt">' + (E ? 'Мы берём всё на себя' : 'We handle everything') + '</div><p class="pp">' + (E ? 'Бронирования, ваучеры, трансферы, поддержка на месте — от начала до конца.' : 'Bookings, vouchers, transfers, on-ground support — from start to finish.') + '</p></div></div></div></section>' +

  // Testimonials
  '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Отзывы' : 'Testimonials') + '</div><h2 class="stitle">' + (E ? 'Что говорят наши партнёры' : 'What our partners say') + '</h2></div>' + testimonials() + '</div></section>' +

  trustBadges() +
  partnerForm();
}
