import { getLang } from '../state.js';
import { COUNTRIES } from '../data/countries.js';
import { partnerForm } from '../components/partnerForm.js';
import { testimonials, trustBadges } from '../components/testimonials.js';
import { seasonCalendar } from '../components/calendar.js';
import { trustBar, whyPartner } from '../components/trustBar.js';

export function renderCountry(c) {
  const L = c[getLang()];
  const E = getLang() === 'ru';
  const products = [
    { ic: '🏨', bg: 'var(--c1l)', t: E ? 'Отели' : 'Hotels', p: E ? 'Широкий выбор по конкурентным нетто.' : 'Wide selection at competitive net rates.' },
    { ic: '🚗', bg: 'var(--c2l)', t: E ? 'Трансферы' : 'Transfers', p: E ? 'Аэропорт, межгород, частный водитель.' : 'Airport, intercity, private chauffeur.' },
    { ic: '🎫', bg: 'var(--c3l)', t: E ? 'Билеты' : 'Tickets', p: E ? 'Аттракции, парки, музеи по нетто.' : 'Attractions, parks, museums at net rates.' },
    { ic: '🏜️', bg: 'var(--gdl)', t: E ? 'Экскурсии' : 'Excursions', p: E ? 'Гиды, культура, приключения.' : 'Guided tours, culture, adventure.' },
    { ic: '🛥️', bg: '#F3E8FF', t: E ? 'Премиум и VIP' : 'Premium & VIP', p: E ? 'Яхты, вертолёты, эксклюзив.' : 'Yachts, helicopters, exclusive.' },
    { ic: '📦', bg: '#FFF1F0', t: E ? 'Пакеты' : 'Packages', p: E ? 'Готовые и кастомные.' : 'Ready-made and customizable.' }
  ];
  const cName = E ? c.nr : c.n;
  const seoH1 = {
    uae: { en: 'UAE DMC Partner — Hotels, Tours & Transfers in Dubai & Abu Dhabi', ru: 'DMC Партнёр в ОАЭ — Отели, туры и трансферы в Дубае и Абу-Даби' },
    thailand: { en: 'Thailand DMC Partner — Hotels & Tours in Bangkok, Phuket & Koh Samui', ru: 'DMC Партнёр в Таиланде — Отели и туры в Бангкоке, Пхукете и Самуи' },
    vietnam: { en: 'Vietnam DMC Partner — Hotels, Cruises & Tours in Hanoi & Ho Chi Minh', ru: 'DMC Партнёр во Вьетнаме — Отели, круизы и туры в Ханое и Хошимине' },
    china: { en: 'China DMC Partner — Hotels, Group Tours & Transfers in Beijing & Shanghai', ru: 'DMC Партнёр в Китае — Отели, групповые туры в Пекине и Шанхае' },
    turkey: { en: 'Turkey DMC Partner — Hotels & Tours in Istanbul, Antalya & Cappadocia', ru: 'DMC Партнёр в Турции — Отели и туры в Стамбуле, Анталии и Каппадокии' },
    egypt: { en: 'Egypt DMC Partner — Hotels, Nile Cruises & Tours in Cairo & Sharm', ru: 'DMC Партнёр в Египте — Отели, круизы по Нилу и туры в Каире и Шарме' },
    europe: { en: 'Europe DMC Partner — Hotels & Multi-Country Tours in Paris, Rome & More', ru: 'DMC Партнёр в Европе — Отели и мульти-страновые туры в Париже, Риме' },
    maldives: { en: 'Maldives DMC Partner — Luxury Resorts & Overwater Villa Packages', ru: 'DMC Партнёр на Мальдивах — Люкс-резорты и виллы над водой' },
    japan: { en: 'Japan DMC Partner — Hotels, Ryokans & Tours in Tokyo & Kyoto', ru: 'DMC Партнёр в Японии — Отели, рёканы и туры в Токио и Киото' },
    indonesia: { en: 'Indonesia DMC Partner — Hotels, Villas & Tours in Bali & Komodo', ru: 'DMC Партнёр в Индонезии — Отели, виллы и туры на Бали и Комодо' },
    mauritius: { en: 'Mauritius DMC Partner — Luxury Resorts & Honeymoon Packages', ru: 'DMC Партнёр на Маврикии — Люкс-резорты и свадебные пакеты' }
  };
  const h1Text = seoH1[c.id] ? seoH1[c.id][getLang()] : cName;
  return '<section class="d-hero"><div class="d-hero-bg" role="img" aria-label="' + c.n + ' travel destination" style="background-image:url(\'' + c.img + '\')"></div><div class="d-hero-c"><div style="font-size:56px;margin-bottom:8px">' + c.flag + '</div><h1>' + h1Text + '</h1><p>' + L.h + '</p></div></section>' +
    '<div class="live"><div class="live-i"><div class="live-item"><div class="live-dot"></div>' + (E ? 'Местное время' : 'Local time') + ': <span class="val" id="ct">--:--</span></div><div class="live-item">🌡 ' + c.wth + '</div><div class="live-item">💱 1 USD = <span class="val">' + c.rate + ' ' + c.cur + '</span></div><div class="live-item">🏛 ' + (E ? 'Столица' : 'Capital') + ': <span class="val">' + c.cap + '</span></div></div></div>' +
    '<section class="d-about"><div class="con"><div class="d-about-txt"><div class="stag">' + (E ? 'Откройте ' + cName : 'Discover ' + c.n) + '</div><h2>' + (E ? 'Ваш DMC-партнёр по ' + cName : 'Your DMC partner for ' + c.n) + '</h2><p>' + L.d1 + '</p><p>' + L.d2 + '</p></div><div class="d-about-img"><img loading="lazy" src="' + c.about_img + '" alt="' + c.n + '"></div></div></section>' +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Ключевые города' : 'Key destinations') + '</div><h2 class="stitle">' + (E ? 'Исследуйте ' + cName : 'Explore ' + c.n) + '</h2></div><div class="cities-grid">' + c.cities.map(function (ci) { return '<div class="city-card"><img loading="lazy" src="' + ci.img + '" alt="' + ci.n + '"><div class="city-ov"><div class="city-n">' + ci.n + '</div><div class="city-s">' + ci.s + '</div></div></div>'; }).join('') + '</div></div></section>' +
    '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Портфель продуктов' : 'Product portfolio') + '</div><h2 class="stitle">' + (E ? 'Что продавать в ' + cName : 'What you can sell in ' + c.n) + '</h2></div><div class="prod-grid">' + products.map(function (p) { return '<div class="prod"><div class="prod-ic" style="background:' + p.bg + '">' + p.ic + '</div><div class="prod-t">' + p.t + '</div><p class="prod-p">' + p.p + '</p></div>'; }).join('') + '</div></div></section>' +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Популярные туры' : 'Popular tours') + '</div><h2 class="stitle">' + (E ? 'Бестселлеры ' + cName : 'Bestselling ' + c.n + ' experiences') + '</h2></div><div class="tour-grid">' + c.tours.map(function (t) { return '<div class="tour"><div class="tour-img"><img loading="lazy" src="' + t.img + '" alt="' + t.t + '"><div class="tour-dur">' + t.d + '</div></div><div class="tour-b"><div class="tour-t">' + (E && t.tr ? t.tr : t.t) + '</div><p class="tour-p">' + (E && t.pr ? t.pr : t.p) + '</p></div></div>'; }).join('') + '</div></div></section>' +
    '<section style="padding:40px 0"><div style="max-width:var(--mx);margin:0 auto"><div class="photo-strip">' + c.photos.map(function (p) { return '<img loading="lazy" src="' + p + '" alt="' + c.n + '">'; }).join('') + '</div></div></section>' +
    '<section class="usp"><div class="usp-c"><div class="usp-h"><div class="stag" style="color:var(--c1)">' + (E ? 'Преимущества партнёра' : 'Partner advantages') + '</div><h2>' + (E ? 'Почему ' + cName + ' через Desera' : 'Why sell ' + c.n + ' through Desera') + '</h2></div><div class="usp-grid">' + c.usp.map(function (u) { return '<div class="usp-card"><div class="usp-num">' + u.n + '</div><div class="usp-t">' + u.t + '</div><p class="usp-p">' + u.p + '</p></div>'; }).join('') + '</div><div style="text-align:center;margin-top:40px"><button class="bp" data-nav="partner" style="background:#fff;color:var(--dk)">' + (E ? 'Начните продавать ' + cName + ' \u2192' : 'Start selling ' + c.n + ' today \u2192') + '</button></div></div></section>' +
    faqSection(c, cName, L, E) +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Для агента' : 'Agent toolkit') + '</div><h2 class="stitle">' + (E ? 'Важное о ' + cName : 'Essential ' + c.n + ' info') + '</h2></div><div class="info-grid"><div class="info-card"><div class="info-ic">🛂</div><div class="info-t">' + (E ? 'Виза' : 'Visa') + '</div><div class="info-v">' + L.visa + '</div></div><div class="info-card"><div class="info-ic">☀️</div><div class="info-t">' + (E ? 'Сезон' : 'Best season') + '</div><div class="info-v">' + L.season + '</div></div><div class="info-card"><div class="info-ic">⏰</div><div class="info-t">' + (E ? 'Часовой пояс' : 'Time zone') + '</div><div class="info-v">' + c.tz + '</div></div><div class="info-card"><div class="info-ic">💡</div><div class="info-t">' + (E ? 'Советы' : 'Tips') + '</div><div class="info-v">' + L.tips + '</div></div></div></div></section>' +
    trustBar() +
    whyPartner() +
    destinationsGrid() +
    servicesSection() +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Отзывы партнёров' : 'Partner testimonials') + '</div><h2 class="stitle">' + (E ? 'Что говорят наши партнёры' : 'What our partners say') + '</h2></div>' + testimonials() + '</div></section>' +
    trustBadges() +
    '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Сезонный календарь' : 'Seasonal calendar') + '</div><h2 class="stitle">' + (E ? 'Когда лучше ехать' : 'Best time to travel') + '</h2></div>' + seasonCalendar() + '</div></section>' +
    partnerForm();
}

function destinationsGrid() {
  const E = getLang() === 'ru';
  return '<section class="sec" id="dest" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Направления' : 'Destinations') + '</div><h2 class="stitle">' + (E ? 'Куда мы отправляем ваших клиентов' : 'Where we take your clients') + '</h2></div><div class="dgrid">' + COUNTRIES.map(function (c) { return '<div class="dc" data-nav="' + c.id + '" style="cursor:pointer;background-image:url(\'' + c.img + '\');background-size:cover;background-position:center"><div class="dc-ov"><div class="dc-fl">' + c.flag + '</div><div class="dc-n">' + (E ? c.nr : c.n) + '</div><div class="dc-s">' + c.sub + '</div></div></div>'; }).join('') + '<div style="grid-column:span 2;border-radius:20px;background:linear-gradient(135deg,var(--c1),#E87B4C);padding:48px 40px;display:flex;flex-direction:column;justify-content:center;cursor:pointer;transition:all .4s;position:relative;overflow:hidden" data-nav="partner" onmouseover="this.style.transform=\'translateY(-4px)\'" onmouseout="this.style.transform=\'none\'"><div style="position:absolute;top:-30px;right:-30px;width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,.1)"></div><div style="position:absolute;bottom:-40px;right:60px;width:80px;height:80px;border-radius:50%;background:rgba(255,255,255,.06)"></div><div style="position:relative;z-index:2"><div style="font-size:32px;margin-bottom:16px">✈️</div><div style="font-family:var(--fd);font-size:28px;color:#fff;margin-bottom:8px">' + (E ? 'Нужно другое направление?' : 'Need a different destination?') + '</div><div style="font-size:15px;color:rgba(255,255,255,.8);margin-bottom:20px;font-weight:300;max-width:360px">' + (E ? 'Мы работаем с любыми запросами. Расскажите нам — мы найдём решение.' : 'We handle any request. Tell us what you need — we\'ll find a solution.') + '</div><div style="display:inline-flex;align-items:center;gap:8px;padding:12px 28px;background:#fff;color:var(--c1);border-radius:100px;font-size:14px;font-weight:600">' + (E ? 'Отправить запрос \u2192' : 'Send a request \u2192') + '</div></div></div></div></div></section>';
}

function faqSection(c, cName, L, E) {
  const faqData = {
    uae: {
      en: [
        { q: 'Do I need a visa to visit the UAE?', a: 'Most nationalities receive a 30-day visa on arrival at Dubai and Abu Dhabi airports free of charge. Citizens of GCC countries do not need a visa at all. For extended stays, 90-day tourist visas are available. Business travelers can apply for multi-entry visas valid for up to 5 years. We recommend checking the latest UAE immigration requirements through your local embassy, as policies are updated frequently. Desera Travel assists B2B partners with group visa processing for tour groups of 10+ travelers.' },
        { q: 'What is the best time to visit the UAE?', a: 'The best time to visit the UAE is from October to April, when temperatures range between 20-30°C — ideal for outdoor activities, desert safaris, and beach holidays. The peak tourist season runs from December to February, coinciding with events like Dubai Shopping Festival and Abu Dhabi Grand Prix. Summer months (June-September) bring extreme heat above 45°C, but offer significantly lower hotel rates — up to 40-60% off peak pricing. For travel agencies, summer packages targeting indoor attractions (malls, theme parks, waterparks) can still deliver strong margins.' },
        { q: 'What are the top tourist attractions in the UAE?', a: 'The UAE offers world-class attractions for every traveler segment. In Dubai: Burj Khalifa (the world\'s tallest building), Palm Jumeirah, Dubai Mall, Desert Safari experiences, and Dubai Marina. In Abu Dhabi: Sheikh Zayed Grand Mosque, Louvre Abu Dhabi, Yas Island theme parks (Ferrari World, Warner Bros), and the Corniche. For adventure seekers: dune bashing, skydiving over the Palm, and deep-sea fishing. Luxury travelers enjoy private yacht cruises, helicopter tours, and exclusive beach clubs. Desera Travel provides instant booking for all major attractions at net rates.' },
        { q: 'What currency is used in the UAE and how much should I budget?', a: 'The official currency is the UAE Dirham (AED), pegged to the US Dollar at a fixed rate of 1 USD = 3.67 AED. US Dollars are widely accepted at hotels, malls, and tourist areas. Credit cards (Visa, Mastercard) are accepted almost everywhere. ATMs are readily available. A mid-range daily budget is approximately 500-800 AED ($135-$220) per person including hotel, meals, and transport. Luxury travelers should budget 2,000+ AED ($545+) per day. Tipping is customary: 10-15% in restaurants and 10-20 AED for hotel staff.' },
        { q: 'Why choose Desera Travel as your DMC partner in the UAE?', a: 'Desera Travel is a Dubai-based Destination Management Company with direct contracts across 300+ hotels, from budget to ultra-luxury properties including Jumeirah, Atlantis, and Address Hotels. We offer competitive net rates with instant confirmation, a dedicated B2B booking platform, and 24/7 on-ground support in Arabic, English, and Russian. Our response time guarantee is under 2 hours for any inquiry. We handle hotels, transfers, excursions, attraction tickets, premium experiences (yachts, helicopters, VIP services), and fully customizable packages. Whether your clients need a family holiday, honeymoon, corporate retreat, or luxury escape — we deliver end-to-end solutions with the best margins for your agency.' }
      ],
      ru: [
        { q: 'Нужна ли виза для поездки в ОАЭ?', a: 'Граждане большинства стран получают бесплатную визу по прибытии на 30 дней в аэропортах Дубая и Абу-Даби. Граждане стран ССАГПЗ не нуждаются в визе. Для длительного пребывания доступны 90-дневные туристические визы. Бизнес-путешественники могут оформить мультивизу сроком до 5 лет. Рекомендуем проверять актуальные требования через посольство. Desera Travel помогает B2B-партнёрам с групповыми визами для групп от 10+ человек.' },
        { q: 'Когда лучше всего ехать в ОАЭ?', a: 'Лучшее время для поездки в ОАЭ — с октября по апрель, когда температура составляет 20-30°C — идеально для пляжного отдыха, сафари и прогулок. Пиковый сезон — декабрь-февраль, совпадает с Dubai Shopping Festival и Гран-при Абу-Даби. Летние месяцы (июнь-сентябрь) отличаются жарой выше 45°C, но цены на отели падают на 40-60%. Для агентств летние пакеты с акцентом на крытые развлечения (моллы, аквапарки, тематические парки) приносят хорошую маржу.' },
        { q: 'Какие главные достопримечательности ОАЭ?', a: 'ОАЭ предлагают аттракции мирового уровня. Дубай: Бурдж-Халифа (самое высокое здание мира), Палм Джумейра, Дубай Молл, пустынные сафари, Дубай Марина. Абу-Даби: мечеть Шейха Зайда, Лувр Абу-Даби, остров Яс (Ferrari World, Warner Bros), набережная Корниш. Для любителей приключений: езда по дюнам, скайдайвинг над Пальмой, глубоководная рыбалка. VIP-клиенты выбирают яхт-круизы, вертолётные экскурсии и пляжные клубы. Desera Travel обеспечивает моментальное бронирование всех аттракций по нетто-ценам.' },
        { q: 'Какая валюта в ОАЭ и какой бюджет планировать?', a: 'Официальная валюта — дирхам ОАЭ (AED), привязан к доллару: 1 USD = 3.67 AED. Доллары принимают в отелях, моллах и туристических зонах. Кредитные карты (Visa, Mastercard) работают повсеместно. Банкоматы доступны везде. Средний бюджет на день — 500-800 AED ($135-$220) включая отель, еду и транспорт. Для люкс-сегмента — от 2,000 AED ($545+) в день. Чаевые приняты: 10-15% в ресторанах, 10-20 AED персоналу отеля.' },
        { q: 'Почему выбрать Desera Travel как DMC-партнёра в ОАЭ?', a: 'Desera Travel — DMC-компания с офисом в Дубае и прямыми контрактами с 300+ отелями, от бюджетных до ультра-люкс (Jumeirah, Atlantis, Address Hotels). Мы предлагаем конкурентные нетто-тарифы с моментальным подтверждением, B2B-платформу для бронирования и поддержку 24/7 на арабском, английском и русском языках. Гарантия ответа — менее 2 часов. Мы закрываем отели, трансферы, экскурсии, билеты, VIP-услуги (яхты, вертолёты) и кастомные пакеты. Семейный отдых, медовый месяц, корпоратив или люкс-отдых — мы обеспечиваем полный цикл с лучшей маржой для вашего агентства.' }
      ]
    },
    thailand: {
      en: [
        { q: 'Do I need a visa to visit Thailand?', a: 'Citizens of most countries can enter Thailand visa-free for 30-60 days. This includes travelers from the EU, UK, US, Australia, and many Asian countries. For longer stays, tourist visas (60 days, extendable) can be obtained at Thai embassies. Visa-on-arrival is available for some nationalities for 15-30 days. Since 2024, Thailand has expanded its visa-free arrangements significantly. Group tours of 10+ travelers from select countries may qualify for simplified entry. Desera Travel helps B2B partners navigate visa requirements for group bookings across all market segments.' },
        { q: 'What is the best time to visit Thailand?', a: 'The best time to visit Thailand is from November to March — the cool, dry season with temperatures around 25-32°C. This is peak season for beach destinations like Phuket, Koh Samui, and Krabi. The shoulder season (April-May) brings hotter weather but fewer crowds and lower prices. The monsoon season (June-October) varies by region: the east coast (Koh Samui, Koh Phangan) is best July-September, while the west coast (Phuket, Krabi) gets rain. Bangkok and Chiang Mai are best November-February. For travel agencies, off-peak packages can offer 30-50% better hotel rates with strong margins.' },
        { q: 'What are the top tourist attractions in Thailand?', a: 'Thailand is one of the world\'s most visited countries with diverse attractions. Bangkok: Grand Palace, Wat Pho (Reclining Buddha), floating markets, Chatuchak Market, vibrant street food scene. Phuket: Patong Beach, Phi Phi Islands, James Bond Island, world-class diving. Chiang Mai: Doi Suthep temple, elephant sanctuaries, night bazaars, Thai cooking classes. Koh Samui: luxury beach resorts, Ang Thong Marine Park. Cultural highlights include Ayutthaya historical parks and White Temple in Chiang Rai. Desera Travel offers 30+ ready-made tour packages and custom itineraries with licensed local guides.' },
        { q: 'What currency is used in Thailand and how much should I budget?', a: 'The official currency is the Thai Baht (THB). Current exchange rate: approximately 1 USD = 34.5 THB. Thailand is known for excellent value — a mid-range daily budget is 2,000-4,000 THB ($60-$115) per person including comfortable hotel, meals, and local transport. Budget travelers can manage on 1,000-1,500 THB ($30-$45) per day. Luxury travelers should budget 10,000+ THB ($290+) for 5-star resorts, fine dining, and private tours. Street food costs 40-100 THB per dish, while restaurant meals range 200-500 THB. Credit cards are accepted at hotels and malls; cash is preferred at markets and smaller shops.' },
        { q: 'Why choose Desera Travel as your DMC partner in Thailand?', a: 'Desera Travel operates with a dedicated Bangkok-based team offering 24/7 Thai and English-speaking support. We maintain direct contracts with 200+ hotels and resorts across Bangkok, Phuket, Koh Samui, Chiang Mai, and Krabi — from boutique guesthouses to luxury beach resorts. Our catalog includes 30+ pre-built tour packages covering temples, islands, cooking classes, elephant sanctuaries, and nightlife. We provide competitive net rates with instant confirmation, airport transfers in all major cities, and VIP services including private speedboats and helicopter transfers. Our B2B platform allows real-time availability checks and one-click booking for your agency.' }
      ],
      ru: [
        { q: 'Нужна ли виза для поездки в Таиланд?', a: 'Граждане большинства стран могут въезжать в Таиланд без визы на 30-60 дней, включая ЕС, Великобританию, США, Австралию и многие азиатские страны. Для более длительного пребывания туристическая виза (60 дней, с продлением) оформляется в посольствах. Виза по прибытии доступна для ряда стран на 15-30 дней. С 2024 года Таиланд значительно расширил безвизовые соглашения. Групповые туры от 10+ человек могут получить упрощённый въезд. Desera Travel помогает B2B-партнёрам с визовыми вопросами для групповых бронирований.' },
        { q: 'Когда лучше всего ехать в Таиланд?', a: 'Лучшее время — с ноября по март (сухой сезон, 25-32°C). Это пик для пляжных направлений: Пхукет, Самуи, Краби. Межсезонье (апрель-май) — жарче, но меньше туристов и ниже цены. Сезон дождей (июнь-октябрь) различается по регионам: восточное побережье (Самуи, Панган) лучше июль-сентябрь, западное (Пхукет, Краби) — дождливее. Бангкок и Чиангмай оптимальны ноябрь-февраль. Для агентств пакеты в низкий сезон дают на 30-50% лучшие цены на отели с высокой маржой.' },
        { q: 'Какие главные достопримечательности Таиланда?', a: 'Таиланд — одна из самых посещаемых стран мира. Бангкок: Большой дворец, Ват Пхо (Лежащий Будда), плавучие рынки, Чатучак, стритфуд. Пхукет: Патонг, острова Пхи-Пхи, остров Джеймса Бонда, дайвинг мирового класса. Чиангмай: храм Дой Сутхеп, слоновьи заповедники, кулинарные классы. Самуи: люкс-курорты, морской парк Анг Тонг. Desera Travel предлагает 30+ готовых турпакетов и индивидуальные маршруты с лицензированными гидами.' },
        { q: 'Какая валюта в Таиланде и какой бюджет планировать?', a: 'Официальная валюта — тайский бат (THB). Курс: примерно 1 USD = 34.5 THB. Таиланд славится отличным соотношением цены и качества. Средний бюджет: 2,000-4,000 THB ($60-$115) в день включая отель, еду и транспорт. Бюджетные путешественники — 1,000-1,500 THB ($30-$45). Люкс — от 10,000 THB ($290+) за 5-звёздочные резорты. Уличная еда: 40-100 THB за блюдо, рестораны: 200-500 THB. Карты принимают в отелях и моллах, на рынках предпочитают наличные.' },
        { q: 'Почему выбрать Desera Travel как DMC-партнёра в Таиланде?', a: 'Desera Travel работает с выделенной командой в Бангкоке, обеспечивая поддержку 24/7 на тайском, английском и русском. Прямые контракты с 200+ отелями в Бангкоке, Пхукете, Самуи, Чиангмае и Краби — от бутиковых до люкс-резортов. Каталог из 30+ готовых туров: храмы, острова, кулинарные классы, слоновьи заповедники. Конкурентные нетто-тарифы с моментальным подтверждением, трансферы во всех городах, VIP-услуги включая частные катера и вертолёты. B2B-платформа с проверкой наличия в реальном времени.' }
      ]
    }
  };

  // For countries without custom FAQ, generate from existing data
  var faqs;
  if (faqData[c.id] && faqData[c.id][getLang()]) {
    faqs = faqData[c.id][getLang()];
  } else {
    var topTours = c.tours.slice(0, 3).map(function(t) { return t.t; }).join(', ');
    var topCities = c.cities.map(function(ci) { return ci.n; }).join(', ');
    var uspText = c.usp.map(function(u) { return u.n + ' ' + u.t; }).join(', ');
    faqs = E ? [
      { q: 'Нужна ли виза для поездки в ' + cName + '?', a: L.visa + ' Desera Travel помогает партнёрам с визовой поддержкой для групповых бронирований. Мы предоставляем актуальную информацию по визовым требованиям и помогаем с оформлением документов для группы от 10+ человек. Рекомендуем проверять требования через посольство перед поездкой.' },
      { q: 'Когда лучше всего ехать в ' + cName + '?', a: L.season + ' В пиковый сезон рекомендуется бронировать отели за 2-3 месяца. Для агентств межсезонье предлагает значительно более низкие тарифы на отели — до 30-50% дешевле пика — при сохранении высокой маржинальности. Desera Travel предоставляет актуальные сезонные предложения через B2B-платформу.' },
      { q: 'Какие главные достопримечательности в ' + cName + '?', a: 'Ключевые города для посещения: ' + topCities + '. Среди самых популярных туров и экскурсий: ' + topTours + '. ' + L.d1 + ' ' + L.d2 + ' Desera Travel предлагает бронирование всех основных аттракций по нетто-тарифам с моментальным подтверждением через B2B-платформу.' },
      { q: 'Какая валюта в ' + cName + ' и какой бюджет планировать?', a: 'Официальная валюта — ' + c.cur + '. Актуальный курс: 1 USD = ' + c.rate + ' ' + c.cur + '. Рекомендуем иметь местную валюту для рынков и мелких покупок. Кредитные карты Visa и Mastercard принимаются в большинстве отелей, ресторанов и торговых центров. Банкоматы широко доступны. Desera Travel предоставляет нетто-тарифы в USD для удобства расчётов с партнёрами.' },
      { q: 'Почему выбрать Desera Travel как DMC-партнёра в ' + cName + '?', a: 'Desera Travel — глобальная DMC-компания с прямыми контрактами и локальной командой. Наши преимущества в ' + cName + ': ' + uspText + '. Мы обеспечиваем конкурентные нетто-тарифы на отели, трансферы, экскурсии и VIP-услуги. Гарантия ответа — менее 2 часов на любой запрос. B2B-платформа с проверкой наличия в реальном времени и моментальным подтверждением. Поддержка на русском и английском языках 24/7.' }
    ] : [
      { q: 'Do I need a visa to visit ' + c.n + '?', a: L.visa + ' Desera Travel assists B2B partners with visa support for group bookings. We provide up-to-date visa requirement information and help with documentation for groups of 10+ travelers. We recommend verifying requirements through the relevant embassy before travel.' },
      { q: 'What is the best time to visit ' + c.n + '?', a: L.season + ' During peak season, we recommend booking hotels 2-3 months in advance. For travel agencies, the shoulder season offers significantly lower hotel rates — up to 30-50% below peak pricing — while maintaining strong margins. Desera Travel provides seasonal deals and promotions through our B2B booking platform.' },
      { q: 'What are the top tourist attractions in ' + c.n + '?', a: 'Key cities to visit include ' + topCities + '. Among the most popular tours and excursions: ' + topTours + '. ' + L.d1 + ' ' + L.d2 + ' Desera Travel offers instant booking for all major attractions at competitive net rates through our B2B platform.' },
      { q: 'What currency is used in ' + c.n + ' and how much should I budget?', a: 'The official currency is ' + c.cur + '. Current exchange rate: 1 USD = ' + c.rate + ' ' + c.cur + '. We recommend carrying local currency for markets and small purchases. Visa and Mastercard credit cards are accepted at most hotels, restaurants, and shopping centers. ATMs are widely available. Desera Travel provides net rates in USD for convenient partner billing.' },
      { q: 'Why choose Desera Travel as your DMC partner in ' + c.n + '?', a: 'Desera Travel is a global Destination Management Company with direct contracts and local ground teams. Our advantages in ' + c.n + ': ' + uspText + '. We provide competitive net rates on hotels, transfers, excursions, and VIP services. Our response guarantee is under 2 hours for any inquiry. Our B2B platform offers real-time availability checks and instant confirmation. Support available 24/7 in English and Russian.' }
    ];
  }

  return '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Часто задаваемые вопросы' : 'Frequently asked questions') + '</div><h2 class="stitle">' + (E ? 'FAQ — ' + cName : 'FAQ — ' + c.n) + '</h2></div><div class="faq-list">' +
    faqs.map(function(f) {
      return '<details class="faq-item anim"><summary class="faq-q">' + f.q + '</summary><div class="faq-a"><p>' + f.a + '</p></div></details>';
    }).join('') +
    '</div></div></section>';
}

function servicesSection() {
  const E = getLang() === 'ru';
  return '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Услуги' : 'Services') + '</div><h2 class="stitle">' + (E ? 'Всё для ваших клиентов' : 'Everything your clients need') + '</h2></div><div class="sgrid"><div class="sv"><div class="sv-img"><img loading="lazy" src="https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=600"></div><div class="sv-b"><div class="sv-t">' + (E ? 'Турпакеты' : 'Travel packages') + '</div><p class="sv-p">' + (E ? 'Мульти-направленные, кастомизируемые пакеты.' : 'Multi-destination, customizable packages.') + '</p></div></div><div class="sv"><div class="sv-img"><img loading="lazy" src="https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600"></div><div class="sv-b"><div class="sv-t">' + (E ? 'Экскурсии и туры' : 'Excursions & tours') + '</div><p class="sv-p">' + (E ? 'От прогулок до экспедиций.' : 'City walks to expeditions.') + '</p></div></div><div class="sv"><div class="sv-img"><img loading="lazy" src="https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600"></div><div class="sv-b"><div class="sv-t">' + (E ? 'Премиум-опыт' : 'Premium experiences') + '</div><p class="sv-p">' + (E ? 'Яхты, вертолёты, VIP.' : 'Yachts, helicopters, VIP.') + '</p></div></div></div></div></section>';
}
