import { getLang } from '../state.js';
import { COUNTRIES } from '../data/countries.js';
import { partnerForm } from '../components/partnerForm.js';
import { testimonials, trustBadges } from '../components/testimonials.js';
import { seasonCalendar } from '../components/calendar.js';
import { trustBar, whyPartner } from '../components/trustBar.js';

export function renderCountry(c) {
  const L = c[getLang()];
  const E = getLang() === 'ru';
  const products = [
    { ic: '🏨', bg: 'var(--c1l)', t: E ? 'Отели' : 'Hotels', p: E ? 'Широкий выбор по конкурентным нетто.' : 'Wide selection at competitive net rates.' },
    { ic: '🚗', bg: 'var(--c2l)', t: E ? 'Трансферы' : 'Transfers', p: E ? 'Аэропорт, межгород, частный водитель.' : 'Airport, intercity, private chauffeur.' },
    { ic: '🎫', bg: 'var(--c3l)', t: E ? 'Билеты' : 'Tickets', p: E ? 'Аттракции, парки, музеи по нетто.' : 'Attractions, parks, museums at net rates.' },
    { ic: '🏜️', bg: 'var(--gdl)', t: E ? 'Экскурсии' : 'Excursions', p: E ? 'Гиды, культура, приключения.' : 'Guided tours, culture, adventure.' },
    { ic: '🛥️', bg: '#F3E8FF', t: E ? 'Премиум и VIP' : 'Premium & VIP', p: E ? 'Яхты, вертолёты, эксклюзив.' : 'Yachts, helicopters, exclusive.' },
    { ic: '📦', bg: '#FFF1F0', t: E ? 'Пакеты' : 'Packages', p: E ? 'Готовые и кастомные.' : 'Ready-made and customizable.' }
  ];
  const cName = E ? c.nr : c.n;
  return '<section class="d-hero"><div class="d-hero-bg" style="background-image:url(\'' + c.img + '\')"></div><div class="d-hero-c"><div style="font-size:56px;margin-bottom:8px">' + c.flag + '</div><h1>' + cName + '</h1><p>' + L.h + '</p></div></section>' +
    '<div class="live"><div class="live-i"><div class="live-item"><div class="live-dot"></div>' + (E ? 'Местное время' : 'Local time') + ': <span class="val" id="ct">--:--</span></div><div class="live-item">🌡 ' + c.wth + '</div><div class="live-item">💱 1 USD = <span class="val">' + c.rate + ' ' + c.cur + '</span></div><div class="live-item">🏛 ' + (E ? 'Столица' : 'Capital') + ': <span class="val">' + c.cap + '</span></div></div></div>' +
    '<section class="d-about"><div class="con"><div class="d-about-txt"><div class="stag">' + (E ? 'Откройте ' + cName : 'Discover ' + c.n) + '</div><h2>' + (E ? 'Ваш DMC-партнёр по ' + cName : 'Your DMC partner for ' + c.n) + '</h2><p>' + L.d1 + '</p><p>' + L.d2 + '</p></div><div class="d-about-img"><img loading="lazy" src="' + c.about_img + '" alt="' + c.n + '"></div></div></section>' +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Ключевые города' : 'Key destinations') + '</div><h2 class="stitle">' + (E ? 'Исследуйте ' + cName : 'Explore ' + c.n) + '</h2></div><div class="cities-grid">' + c.cities.map(function (ci) { return '<div class="city-card"><img loading="lazy" src="' + ci.img + '" alt="' + ci.n + '"><div class="city-ov"><div class="city-n">' + ci.n + '</div><div class="city-s">' + ci.s + '</div></div></div>'; }).join('') + '</div></div></section>' +
    '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Портфель продуктов' : 'Product portfolio') + '</div><h2 class="stitle">' + (E ? 'Что продавать в ' + cName : 'What you can sell in ' + c.n) + '</h2></div><div class="prod-grid">' + products.map(function (p) { return '<div class="prod"><div class="prod-ic" style="background:' + p.bg + '">' + p.ic + '</div><div class="prod-t">' + p.t + '</div><p class="prod-p">' + p.p + '</p></div>'; }).join('') + '</div></div></section>' +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Популярные туры' : 'Popular tours') + '</div><h2 class="stitle">' + (E ? 'Бестселлеры ' + cName : 'Bestselling ' + c.n + ' experiences') + '</h2></div><div class="tour-grid">' + c.tours.map(function (t) { return '<div class="tour"><div class="tour-img"><img loading="lazy" src="' + t.img + '" alt="' + t.t + '"><div class="tour-dur">' + t.d + '</div></div><div class="tour-b"><div class="tour-t">' + (E && t.tr ? t.tr : t.t) + '</div><p class="tour-p">' + (E && t.pr ? t.pr : t.p) + '</p></div></div>'; }).join('') + '</div></div></section>' +
    '<section style="padding:40px 0"><div style="max-width:var(--mx);margin:0 auto"><div class="photo-strip">' + c.photos.map(function (p) { return '<img loading="lazy" src="' + p + '" alt="' + c.n + '">'; }).join('') + '</div></div></section>' +
    '<section class="usp"><div class="usp-c"><div class="usp-h"><div class="stag" style="color:var(--c1)">' + (E ? 'Преимущества партнёра' : 'Partner advantages') + '</div><h2>' + (E ? 'Почему ' + cName + ' через Desera' : 'Why sell ' + c.n + ' through Desera') + '</h2></div><div class="usp-grid">' + c.usp.map(function (u) { return '<div class="usp-card"><div class="usp-num">' + u.n + '</div><div class="usp-t">' + u.t + '</div><p class="usp-p">' + u.p + '</p></div>'; }).join('') + '</div><div style="text-align:center;margin-top:40px"><button class="bp" data-nav="partner" style="background:#fff;color:var(--dk)">' + (E ? 'Начните продавать ' + cName + ' \u2192' : 'Start selling ' + c.n + ' today \u2192') + '</button></div></div></section>' +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Для агента' : 'Agent toolkit') + '</div><h2 class="stitle">' + (E ? 'Важное о ' + cName : 'Essential ' + c.n + ' info') + '</h2></div><div class="info-grid"><div class="info-card"><div class="info-ic">🛂</div><div class="info-t">' + (E ? 'Виза' : 'Visa') + '</div><div class="info-v">' + L.visa + '</div></div><div class="info-card"><div class="info-ic">☀️</div><div class="info-t">' + (E ? 'Сезон' : 'Best season') + '</div><div class="info-v">' + L.season + '</div></div><div class="info-card"><div class="info-ic">⏰</div><div class="info-t">' + (E ? 'Часовой пояс' : 'Time zone') + '</div><div class="info-v">' + c.tz + '</div></div><div class="info-card"><div class="info-ic">💡</div><div class="info-t">' + (E ? 'Советы' : 'Tips') + '</div><div class="info-v">' + L.tips + '</div></div></div></div></section>' +
    trustBar() +
    whyPartner() +
    destinationsGrid() +
    servicesSection() +
    '<section class="sec" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Отзывы партнёров' : 'Partner testimonials') + '</div><h2 class="stitle">' + (E ? 'Что говорят наши партнёры' : 'What our partners say') + '</h2></div>' + testimonials() + '</div></section>' +
    trustBadges() +
    '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Сезонный календарь' : 'Seasonal calendar') + '</div><h2 class="stitle">' + (E ? 'Когда лучше ехать' : 'Best time to travel') + '</h2></div>' + seasonCalendar() + '</div></section>' +
    partnerForm();
}

function destinationsGrid() {
  const E = getLang() === 'ru';
  return '<section class="sec" id="dest" style="background:#fff"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Направления' : 'Destinations') + '</div><h2 class="stitle">' + (E ? 'Куда мы отправляем ваших клиентов' : 'Where we take your clients') + '</h2></div><div class="dgrid">' + COUNTRIES.map(function (c) { return '<div class="dc" data-nav="' + c.id + '" style="cursor:pointer;background-image:url(\'' + c.img + '\');background-size:cover;background-position:center"><div class="dc-ov"><div class="dc-fl">' + c.flag + '</div><div class="dc-n">' + (E ? c.nr : c.n) + '</div><div class="dc-s">' + c.sub + '</div></div></div>'; }).join('') + '<div style="grid-column:span 2;border-radius:20px;background:linear-gradient(135deg,var(--c1),#E87B4C);padding:48px 40px;display:flex;flex-direction:column;justify-content:center;cursor:pointer;transition:all .4s;position:relative;overflow:hidden" data-nav="partner" onmouseover="this.style.transform=\'translateY(-4px)\'" onmouseout="this.style.transform=\'none\'"><div style="position:absolute;top:-30px;right:-30px;width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,.1)"></div><div style="position:absolute;bottom:-40px;right:60px;width:80px;height:80px;border-radius:50%;background:rgba(255,255,255,.06)"></div><div style="position:relative;z-index:2"><div style="font-size:32px;margin-bottom:16px">✈️</div><div style="font-family:var(--fd);font-size:28px;color:#fff;margin-bottom:8px">' + (E ? 'Нужно другое направление?' : 'Need a different destination?') + '</div><div style="font-size:15px;color:rgba(255,255,255,.8);margin-bottom:20px;font-weight:300;max-width:360px">' + (E ? 'Мы работаем с любыми запросами. Расскажите нам — мы найдём решение.' : 'We handle any request. Tell us what you need — we\'ll find a solution.') + '</div><div style="display:inline-flex;align-items:center;gap:8px;padding:12px 28px;background:#fff;color:var(--c1);border-radius:100px;font-size:14px;font-weight:600">' + (E ? 'Отправить запрос \u2192' : 'Send a request \u2192') + '</div></div></div></div></div></section>';
}

function servicesSection() {
  const E = getLang() === 'ru';
  return '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Услуги' : 'Services') + '</div><h2 class="stitle">' + (E ? 'Всё для ваших клиентов' : 'Everything your clients need') + '</h2></div><div class="sgrid"><div class="sv"><div class="sv-img"><img loading="lazy" src="https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=600"></div><div class="sv-b"><div class="sv-t">' + (E ? 'Турпакеты' : 'Travel packages') + '</div><p class="sv-p">' + (E ? 'Мульти-направленные, кастомизируемые пакеты.' : 'Multi-destination, customizable packages.') + '</p></div></div><div class="sv"><div class="sv-img"><img loading="lazy" src="https://images.unsplash.com/photo-1558642452-9d2a7deb7f62?w=600"></div><div class="sv-b"><div class="sv-t">' + (E ? 'Экскурсии и туры' : 'Excursions & tours') + '</div><p class="sv-p">' + (E ? 'От прогулок до экспедиций.' : 'City walks to expeditions.') + '</p></div></div><div class="sv"><div class="sv-img"><img loading="lazy" src="https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600"></div><div class="sv-b"><div class="sv-t">' + (E ? 'Премиум-опыт' : 'Premium experiences') + '</div><p class="sv-p">' + (E ? 'Яхты, вертолёты, VIP.' : 'Yachts, helicopters, VIP.') + '</p></div></div></div></div></section>';
}
