import { getLang } from '../state.js';

export function trustBar() {
  const E = getLang() === 'ru';
  return '<div class="trust"><div class="trust-i"><div class="ti"><div class="ti-ic" style="background:var(--c1l)">\uD83C\uDF0D</div><span>' + (E ? '11+ направлений' : '11+ destinations') + '</span></div><div class="ti"><div class="ti-ic" style="background:var(--c2l)">\uD83E\uDD1D</div><span>' + (E ? 'Прямые контракты' : 'Direct contracts') + '</span></div><div class="ti"><div class="ti-ic" style="background:var(--c3l)">\u26A1</div><span>' + (E ? 'B2B-платформа и API' : 'B2B platform & API') + '</span></div><div class="ti"><div class="ti-ic" style="background:var(--gdl)">\uD83C\uDFC6</div><span>' + (E ? 'От массового до luxury' : 'Mass to luxury') + '</span></div></div></div>';
}

export function whyPartner() {
  const E = getLang() === 'ru';
  return '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Почему мы' : 'Why partner with us') + '</div><h2 class="stitle">' + (E ? 'Всё, что нужно вашему агентству' : 'Everything your agency needs') + '</h2></div><div class="pgrid"><div class="pc"><div class="pc-ic" style="background:var(--c1l)">\uD83C\uDF0F</div><div class="pt">' + (E ? 'Глобальное покрытие' : 'Global coverage') + '</div><p class="pp">' + (E ? '11+ направлений через одну точку входа.' : '11+ destinations through one contact.') + '</p></div><div class="pc"><div class="pc-ic" style="background:var(--c2l)">\uD83D\uDCB0</div><div class="pt">' + (E ? 'Конкурентные тарифы' : 'Competitive rates') + '</div><p class="pp">' + (E ? 'Прямые контракты. Лучшие нетто.' : 'Direct contracts. Best net rates.') + '</p></div><div class="pc"><div class="pc-ic" style="background:var(--gdl)">\u2728</div><div class="pt">' + (E ? 'Индивидуальный подход' : 'Tailored experiences') + '</div><p class="pp">' + (E ? 'Каждый запрос — уникальный проект.' : 'Every request is a unique project.') + '</p></div><div class="pc"><div class="pc-ic" style="background:var(--c3l)">\uD83D\uDDA5\uFE0F</div><div class="pt">' + (E ? 'Платформа и API' : 'B2B platform & API') + '</div><p class="pp">' + (E ? 'Бронирование онлайн, дашборд.' : 'Real-time booking, dashboard.') + '</p></div></div><div style="text-align:center;margin-top:56px"><button class="bp" style="padding:20px 40px;font-size:17px;background:linear-gradient(135deg,var(--c1),#E87B4C);box-shadow:0 8px 32px rgba(232,96,76,.25)" data-nav="partner">' + (E ? 'Готовы начать? Давайте обсудим \u2192' : 'Ready to start? Let\'s talk \u2192') + '</button></div></div></section>';
}
