import { getLang } from '../state.js';

export function trustBar() {
  const E = getLang() === 'ru';
  return '<div class="trust"><div class="trust-i"><div class="ti"><div class="ti-ic" style="background:var(--c1l)">\uD83C\uDF0D</div><span>' + (E ? '11+ направлений' : '11+ destinations') + '</span></div><div class="ti"><div class="ti-ic" style="background:var(--c2l)">\uD83E\uDD1D</div><span>' + (E ? 'Прямые контракты' : 'Direct contracts') + '</span></div><div class="ti"><div class="ti-ic" style="background:var(--c3l)">\u26A1</div><span>' + (E ? 'B2B-платформа и API' : 'B2B platform & API') + '</span></div><div class="ti"><div class="ti-ic" style="background:var(--gdl)">\uD83C\uDFC6</div><span>' + (E ? 'От массового до luxury' : 'Mass to luxury') + '</span></div></div></div>';
}

export function whyPartner() {
  var E = getLang() === 'ru';
  return '<section class="sec"><div class="con"><div class="sh"><div class="stag">' + (E ? 'Почему мы' : 'Why partner with us') + '</div><h2 class="stitle">' + (E ? 'Всё, что нужно вашему агентству' : 'Everything your agency needs') + '</h2></div><div class="pgrid"><div class="pc"><div class="pc-ic" style="background:var(--c1l)">\uD83C\uDF0F</div><div class="pt">' + (E ? 'Один контакт — 13 стран' : 'One contact — 13 countries') + '</div><p class="pp">' + (E ? 'Вам не нужно 5 разных DMC. Один менеджер решает всё.' : 'You don\'t need 5 different DMCs. One manager handles everything.') + '</p></div><div class="pc"><div class="pc-ic" style="background:var(--c2l)">\uD83D\uDCB0</div><div class="pt">' + (E ? 'Прямые цены' : 'Direct rates') + '</div><p class="pp">' + (E ? 'Без посредников. Вы покупаете по нетто — продаёте по своей цене.' : 'No middlemen. You buy at net — sell at your price.') + '</p></div><div class="pc"><div class="pc-ic" style="background:var(--gdl)">\u26A1</div><div class="pt">' + (E ? 'Ответ за 2 часа' : 'Response in 2 hours') + '</div><p class="pp">' + (E ? 'Клиент не будет ждать. Мы тоже нет. Максимум 2 часа.' : 'Your client won\'t wait. Neither will we. 2 hours max.') + '</p></div><div class="pc"><div class="pc-ic" style="background:var(--c3l)">\uD83C\uDFF7\uFE0F</div><div class="pt">' + (E ? 'Ваш бренд' : 'Your brand') + '</div><p class="pp">' + (E ? 'Клиент видит только вас. Мы за кулисами. White-label.' : 'The client sees only you. We stay behind the scenes. White-label.') + '</p></div></div><div style="text-align:center;margin-top:56px"><button class="bp" style="padding:20px 40px;font-size:17px;background:linear-gradient(135deg,var(--c1),#E87B4C);box-shadow:0 8px 32px rgba(232,96,76,.25)" data-nav="partner">' + (E ? 'Готовы начать? Давайте обсудим \u2192' : 'Ready to start? Let\'s talk \u2192') + '</button></div></div></section>';
}
